FROM nginx:alpine

COPY index.html /usr/share/nginx/html/index.html
COPY robots.txt /usr/share/nginx/html/robots.txt
COPY backup_admin_panel.html /usr/share/nginx/html/backup_admin_panel.html
COPY config.js /usr/share/nginx/html/config.js

EXPOSE 80
